### ISSUE TITLE
Required to manually start

### ISSUE THREAD

**Issue by Gidget19893161** [alex9849/CocktailPi#42]
Every time I reboot the pi I have to ssh in and manually type "service cocktailpi start" followed by my password.

**Comment by alex9849** [comment]
You need to add the application to the autostart:
```
sudo -i
ln -s /root/cocktailpi/cocktailpi.jar /etc/init.d/cocktailpi
chmod +x /etc/init.d/cocktailpi
systemctl daemon-reload
update-rc.d cocktailpi defaults
```

**Comment by Gidget19893161** [comment]
this is what i got back
`root@CocktailPi:~# sudo -i
root@CocktailPi:~# ln -s /root/cocktailpi/cocktailpi.jar /etc/init.d/cocktailpi
ln: failed to create symbolic link '/etc/init.d/cocktailpi': File exists
root@CocktailPi:~#`

**Comment by alex9849** [comment]
That means that you've already done that step. Just continue with the rest. :)

**Comment by alex9849** [comment]
But run that `sudo -i` in every session. You need be logged in as root or have root privileges when you run the commands.

**Comment by Gidget19893161** [comment]
That seems to have fixed it. I must have missed a step in the original setup! Thank you

**Comment by Gidget19893161** [comment]
That seems to have fixed it. I must have missed a step in the original setup! Thank you
