### ISSUE TITLE
Installing a touch screen

### ISSUE THREAD

**Issue by Gidget19893161** [alex9849/CocktailPi#46]
when trying to install a touchscreen (ROADOM 10.1’’ Raspberry Pi Screen) I am getting an error.

command -  root@raspberrypi:~# apt install --no-install-recommends -y libevent-2.1-7 libvpx6 libgtk-3-common libdbus-glib-1-2

output - 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libvpx6 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libvpx6' has no installation candidate
root@raspberrypi:~#

I have already ran the command. this is the second time. This is also on a fresh install of rasp and cocktail pi.

**Comment by alex9849** [comment]
Hi, you are very likely on the Bookworm version of your operating system. You don't need to run that command. You can just continue with the installation. :)
